// Press coverage. To add a story, copy an entry and change the fields.
//   date:  'YYYY-MM-DD', or just 'YYYY' if the exact day isn't known
//   story: one of the keys in `stories` below

export const stories = {
  blowouts: {
    label: 'Well blowouts and wastewater injection, West Texas',
    summary:
      'Coverage of the Geophysical Research Letters study linking oil well blowouts in the Permian Basin to wastewater injection, and of leaking and erupting abandoned wells in the region.',
    doi: '10.1029/2024GL109435',
  },
  earthquakes: {
    label: 'Induced earthquakes, Delaware Basin',
    summary:
      'Coverage of the SMU-led study that tied West Texas earthquakes before 2017 to oil and gas wastewater injection.',
    doi: '10.1785/0320240011',
  },
  permian: {
    label: 'Ground deformation in the Permian Basin',
    summary:
      'Coverage of the InSAR analysis of ground deformation caused by oil and gas production across the Permian Basin of Texas and New Mexico.',
    doi: '10.1016/j.jag.2023.103424',
  },
  delhi: {
    label: 'Land subsidence in Delhi',
    summary:
      'Coverage of the Scientific Reports study that mapped land subsidence around India’s capital and traced it to groundwater pumping.',
    doi: '10.1038/s41598-021-04193-9',
  },
};

export const media = [
  { date: '2025', story: 'blowouts', outlet: 'Bloomberg', author: null, featured: true,
    title: 'Texas Oil Boom Spawns a Toxic Crisis of the Industry’s Own Making',
    url: 'https://www.bloomberg.com/graphics/2025-permian-basin-geyser/' },
  { date: '2024-11-04', story: 'blowouts', outlet: 'Newsweek', author: 'Chowdhury, S.', featured: true,
    title: 'Well Blowouts in Texas Prompt $100M Emergency Funding Plea',
    url: 'https://www.newsweek.com/texas-oil-blowouts-emergency-funding-leak-railroad-waste-1979859' },
  { date: '2024-10-16', story: 'blowouts', outlet: 'Houston Chronicle', author: 'Drane, A.',
    title: 'Who’s to blame for the geyser still erupting in West Texas? Documents start to unravel mystery.',
    url: 'https://www.houstonchronicle.com/news/investigations/article/geyser-tx-railroad-commission-kinder-morgan-apache-19824265.php' },
  { date: '2024-10-04', story: 'blowouts', outlet: 'DeSmog', author: 'Kelly, S.',
    title: 'Blowout Erupts in West Texas’s Permian Basin, Creating 100-Foot Tower of Oily Water',
    url: 'https://www.desmog.com/2024/10/04/texas-railroad-commission-kinder-morgan-oil-well-blowout-erupts-in-west-texas-permian-basin/' },
  { date: '2024-08-20', story: 'earthquakes', outlet: 'The Dallas Morning News', author: 'Fauzia, M.',
    title: 'Is it natural or fracking? SMU study reveals cause of past Texas earthquakes.',
    url: 'https://www.dallasnews.com/news/2024/08/20/earthquakes-before-2017-tied-to-oil-and-gas-wastewater-scientists-at-smu-find/' },
  { date: '2024-08-20', story: 'blowouts', outlet: 'Houston Chronicle', author: 'Tomlinson, C.',
    title: 'A zombie well apocalypse is coming for the Permian Basin. Texas regulators are not keeping up.',
    url: 'https://www.houstonchronicle.com/business/columnists/tomlinson/article/texas-oil-zombie-well-water-19664264.php' },
  { date: '2024-08-14', story: 'blowouts', outlet: 'Reuters', author: 'Volcovici, V.', featured: true,
    title: 'Texas oil regulator under scrutiny as zombie wells gush back to life.',
    url: 'https://www.reuters.com/business/energy/texas-oil-regulator-under-scrutiny-zombie-wells-gush-back-life-2024-08-14/' },
  { date: '2024-08-14', story: 'blowouts', outlet: 'Fast Company', author: 'Volcovici, V.',
    title: 'Zombie oil wells are springing back to life in Texas. Here’s why.',
    url: 'https://www.fastcompany.com/91172863/zombie-oil-wells-springing-back-to-life-texas' },
  { date: '2024-08-08', story: 'blowouts', outlet: 'Houston Chronicle', author: 'Drane, A.',
    title: 'Study: More well blowouts to come.',
    url: 'https://www.houstonchronicle.com/business/energy/article/zombie-oil-wells-west-texas-blowouts-wastewater-19628728.php' },
  { date: '2024-08-07', story: 'blowouts', outlet: 'Inside Climate News', author: 'Baddour, D.',
    title: 'Study Links Permian Blowouts With Wastewater Injection.',
    url: 'https://insideclimatenews.org/news/07082024/permian-basin-oil-well-blowouts-linked-with-wastewater-injection/' },
  { date: '2024-08-07', story: 'blowouts', outlet: 'The Texas Tribune', author: 'Ramos, N.C.; Baddour, D.', featured: true,
    title: 'Ranchers reported abandoned oil wells spewing wastewater. A new study blames fracking.',
    url: 'https://www.texastribune.org/2024/08/07/texas-oil-fracking-wastewater-injection-blowouts-permian-basin/' },
  { date: '2024-08-07', story: 'earthquakes', outlet: 'Axios Dallas', author: 'Tsiaperas, T.',
    title: 'West Texas quakes occur near drilling sites, SMU finds.',
    url: 'https://www.axios.com/local/dallas/2024/08/07/west-texas-fracking-earthquakes-smu-study' },
  { date: '2024-08-06', story: 'earthquakes', outlet: 'SMU News', author: 'SMU Dallas',
    title: 'Study revisits Texas seismic activity occurring before 2017, confirming connection to wastewater injection.',
    url: 'https://www.smu.edu/news/research/texas-seismic-activity-and-wastewater-injection' },
  { date: '2024-02-29', story: 'blowouts', outlet: 'The Texas Tribune', author: 'Ramos, N.C.; Pskowski, M.',
    title: '“Nobody really knows what you’re supposed to do”: Leaking, exploding abandoned wells wreak havoc in West Texas.',
    url: 'https://www.texastribune.org/2024/02/28/abandoned-oil-wells-west-texas-railroad-commission/' },
  { date: '2024-02-29', story: 'blowouts', outlet: 'Inside Climate News', author: 'Pskowski, M.',
    title: 'West Texas Orphan Wells Are Leaking With Unknown Harms.',
    url: 'https://insideclimatenews.org/news/29022024/abandoned-oil-wells-west-texas-railroad-commission/' },
  { date: '2023-09-07', story: 'permian', outlet: 'Carlsbad Current-Argus', author: 'Hedden, A.',
    title: 'Oil and gas is ‘deforming’ New Mexico’s land, study says.',
    url: 'https://www.currentargus.com/story/news/2023/09/07/oil-gas-new-mexico-permian-basin-delaware-midland-texas-environment-souther-methodist-university/70729375007/' },
  { date: '2023-08-31', story: 'permian', outlet: 'Center for Western Priorities', author: 'Staff',
    title: 'Permian Basin oil and gas activity is increasing geological hazards.',
    url: 'https://westernpriorities.org/2023/08/permian-basin-oil-and-gas-activity-is-increasing-geological-hazards/' },
  { date: '2023-08-30', story: 'permian', outlet: 'NM Political Report', author: 'Grover, H.',
    title: 'Researchers warn that changes in the Permian Basin surface due to oil and gas industry activities are leading to increasing geohazards.',
    url: 'https://nmpoliticalreport.com/2023/08/30/researchers-warn-that-changes-permian-basin-surface-due-to-oil-gas-industry-leading-geohazards/' },
  { date: '2023-01-22', story: 'delhi', outlet: 'BBC', author: null, featured: true,
    title: 'How a Delhi district stopped the ground from sinking.',
    url: 'https://www.bbc.com/news/world-asia-india-64342196' },
  { date: '2022-05-09', story: 'delhi', outlet: 'Nature India', author: 'Alakananda, D.',
    title: 'Groundwater pumping linked to land subsidence in India’s capital.',
    url: 'https://www.nature.com/articles/d44151-022-00048-y' },
  { date: '2022-03-24', story: 'delhi', outlet: 'University of Cambridge', author: 'Dutta, S.R.',
    title: 'Hidden crisis in India’s capital unveiled using satellite data.',
    url: 'http://www.eng.cam.ac.uk/news/hidden-crisis-indias-capital-unveiled-using-satellite-data' },
  { date: '2022-03-18', story: 'delhi', outlet: 'India Water Portal', author: 'Garg, S.; Motagh, M.; Indu, J.; Karanam, V.',
    title: 'Delhi, sinking?',
    url: 'https://www.indiawaterportal.org/articles/delhi-sinking' },
  { date: '2022-01-20', story: 'delhi', outlet: 'AajTak', author: 'ऋचीक मिश्रा', lang: 'hi',
    title: 'Delhi-NCR:...100 वर्ग KM का इलाका.',
    url: 'https://www.aajtak.in/science/photo/delhi-ncr-excessive-groundwater-extraction-causing-sink-know-its-impact-tstr-1396022-2022-01-20-1' },
  { date: '2022-01-18', story: 'delhi', outlet: 'Hindustan Times', author: 'Singh, P.',
    title: 'Excessive groundwater extraction causing parts of Delhi-NCR to sink.',
    url: 'https://www.hindustantimes.com/cities/delhi-news/excessive-groundwater-extraction-causing-parts-delhi-ncr-to-sink-study' },
  { date: '2022-01-18', story: 'delhi', outlet: 'DNA India', author: 'DNA Web Team',
    title: 'Thousands of acres of land in Delhi NCR is sinking, here’s why.',
    url: 'https://www.dnaindia.com/india/report-thousands-of-acres-land-delhi-ncr-is-sinking-here-s-why' },
];
